name: Verificar Vírus

on:
  push:
    branches:
      - aurora  # ou a branch principal do seu repositório
  workflow_dispatch:

jobs:
  verificar_virus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Listar Arquivos no Diretório
        run: ls .github/workflows  # Listar os arquivos no diretório .github/workflows

      - name: Executar Script de Verificação de Vírus
        run: |
          chmod +x .github/workflows/verificar_virus.sh
          ./.github/workflows/verificar_virus.sh
        env:
          VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
