name: Build e Verificações

on:
  push:
    branches:
      - aurora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Adicione aqui os passos de build, compilação e teste necessários para o seu projeto

  verifica_licenca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Instalar Dependências
        run: |
          python -m pip install -r requirements.txt

      - name: Verificar Licença
        run: |
          python -m pip install -q pip-licenses
          pip-licenses

  analise_seguranca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Instalar Dependências
        run: |
          python -m pip install -r requirements.txt

      - name: Análise de Segurança em Dependências
        run: |
          python -m pip install -q safety
          safety check -r requirements.txt

      - name: Análise de Segurança em Código
        run: |
          python -m pip install -q bandit
          bandit -r . -ll

      - name: Análise de Segurança em aurora.py
        run: |
          python -m pip install -q bandit
          bandit -r aurora.py -ll

# Adicione outras jobs e steps conforme necessário para o seu fluxo de trabalho
